set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

#clean:
#  rm -rf ./.venv || true
#  rm Pipfile.lock || true

nix:
  #!/usr/bin/env bash
  set -xeufo pipefail
  nix develop --command zsh

iso:
  #!/usr/bin/env bash
  set -eufo pipefail
  mkdir -p ../iso || true
  curl -o ../iso/ubuntu-24.04.1-live-server-amd64.iso "https://releases.ubuntu.com/24.04.1/ubuntu-24.04.1-live-server-amd64.iso"

unpack:
  #!/usr/bin/env bash
  set -eufo pipefail
  mkdir -p ./image || true
  7z -y x ../iso/ubuntu-24.04.1-live-server-amd64.iso  -oimage

create:
  #!/usr/bin/env bash
  set -eufo pipefail
  virt-install -n ubuntu-autoinstall --ram 4096 --vcpus=2 --cpu=host-model -c ../iso/ubuntu-24.04-custom-autoinstall.iso --os-variant=ubuntu24.04 --graphics=vnc --network bridge=virbr0

list:
  #!/usr/bin/env bash
  set -eufo pipefail
  virsh list --all

connect:
  #!/usr/bin/env bash
  set -eufo pipefail
  virt-viewer --connect qemu:///session --wait ubuntu-autoinstall

destroy:
  #!/usr/bin/env bash
  set -eufo pipefail
  virsh shutdown ubuntu-autoinstall || true
  virsh undefine ubuntu-autoinstall || true
