set dotenv-load := true

export MACHINE_NAME:="ubuntu-testing"
export SOURCE_ISO_NAME:="ubuntu-24.04.1-live-server-amd64.iso"

# default lists actions
default:
  @just -f justfile --list

#clean:
#  rm -rf ./.venv || true
#  rm Pipfile.lock || true

nix:
  #!/usr/bin/env bash
  set -xeufo pipefail
  nix develop --command zsh

iso:
  #!/usr/bin/env bash
  set -eufo pipefail
  mkdir -p ../iso || true
  curl -o ../iso/${SOURCE_ISO_NAME} "https://releases.ubuntu.com/24.04.1/ubuntu-24.04.1-live-server-amd64.iso"

# build a machine using custom image
machine-create name="${MACHINE_NAME}": 
  #!/usr/bin/env bash
  set -eufo pipefail
  virt-install -n {{ name }} --ram 4096 --vcpus=2 --cpu=host-model -c ../iso/${SOURCE_ISO_NAME} --os-variant=ubuntu24.04 --graphics=vnc --network bridge=virbr0

machine-list:
  #!/usr/bin/env bash
  set -eufo pipefail
  virsh list --all
  virsh -c qemu:///system list --all

manager:
  #!/usr/bin/env bash
  set -eufo pipefail
  virt-manager

machine-connect name="${MACHINE_NAME}":
  #!/usr/bin/env bash
  set -eufo pipefail
  virt-viewer --connect qemu:///session --wait {{ name }}

machine-destroy name="${MACHINE_NAME}":
  #!/usr/bin/env bash
  set -eufo pipefail
  # shutdown the machine
  virsh shutdown {{ name }} || true
  echo "Waiting 2 seconds for the machine to shutdown"
  sleep 2
  virsh undefine {{ name }} --remove-all-storage || true

machine-clone name="${MACHINE_NAME}":
  #!/usr/bin/env bash
  set -eufo pipefail
  mkdir -p ./machines || true
  virsh shutdown ${MACHINE_NAME} || true
  sleep 2
  virt-clone --original {{ name }} --auto-clone --name {{ name }}-clone --file ./machines/{{ name }}-clone.qcow2

machine-export name="${MACHINE_NAME}":
  #!/usr/bin/env bash
  set -eufo pipefail
  mkdir -p ./machines || true

  virsh dumpxml {{ name }} > ./machines/{{ name }}.xml
  virsh domblklist {{ name }}

machine-network name="${MACHINE_NAME}":
  #!/usr/bin/env bash
  #set -eufo pipefail
  mkdir -p ./machines || true
  virsh domifaddr {{ name }}
  virsh domifaddr {{ name }} --source agent
  #virsh console {{ name }}